name: feature_quiz
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  core_dao:
    path: ../../core/dao
  core_data:
    path: ../../core/data
  core_repository:
    path: ../../core/repository
  core_utility:
    path: ../../core/utility
  core_router:
    path: ../../core/router
  core_designsystem:
    path: ../../core/designsystem
  core_foundation:
    path: ../../core/foundation
  core_ui:
    path: ../../core/ui
  core_model:
    path: ../../core/model
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  go_router: ^14.2.0
  freezed_annotation: ^2.4.1
  fl_chart: ^0.68.0


  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: 2.5.2
  json_serializable: ^6.8.0

  lints: ^3.0.0
  test: ^1.24.0
