name: core_test_util
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  feature_wordlist:
    path: ../../feature/wordlist
  core_designsystem:
    path: ../designsystem
  core_model:
    path: ../model
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  golden_toolkit: ^0.15.0
  mockito: ^5.4.4


  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  lints: ^3.0.0
  test: ^1.24.0
