name: core_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  core_test_util:
    path: ../test_util
  core_foundation:
    path: ../foundation
  core_model:
    path: ../model
  core_utility:
    path: ../utility
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  riverpod_generator: ^2.4.0
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
