name: core_dao
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  core_foundation:
    path: ../foundation
  core_data:
    path: ../data
  core_repository:
    path: ../repository
  core_ui:
    path: ../ui
  core_utility:
    path:  ../utility
  core_model:
    path: ../model

dev_dependencies:
  build_runner: ^2.3.3
  freezed: 2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
