name: ko_beginner
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.0.2

  core_dao:
    path: ../../packages/core/dao
  core_data:
    path: ../../packages/core/data
  core_constants:
    path: ../../packages/core/constants
  core_views:
    path: ../../packages/core/views
  core_enums:
    path: ../../packages/core/enums
  core_utility:
    path: ../../packages/core/utility
  core_router: 
    path: ../../packages/core/router

  #  feature
  feature_setting:
    path: ../../packages/feature/setting
  feature_quiz:
    path: ../../packages/feature/quiz
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1


flutter:
  assets:
    - assets/
    - ./assets/images/ko_national_flag.png
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  assets:
    - ./assets/launcher_icons/dev.png
    - ./assets/launcher_icons/prd.png
