name: ko_beginner
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.5+2

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.0.2
  #  core　ここは基本　appからは依存しない
  # root 定義
  core_router:  
    path: ../../packages/core/router    
    
  # 合成基点のDI用
  core_repository:
    path: ../../packages/core/repository
  core_service: 
    path: ../../packages/core/service
  
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  flutter_localization: ^0.2.0
  flutter_gen: ^5.6.0
  mockito: ^5.4.4
  permission_handler: ^11.3.1
  flutter_tts: ^4.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  patrol: ^3.7.2
  patrol_finders: 2.1.2


flutter:
  assets:
    - assets/
    - ./assets/images/national_flag.png
    - ./assets/images/national_dark.png
  uses-material-design: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icons/$(FLAVOR).png"


patrol:
  app_name: patrol_integ
  android:
    package_name: com.rensawamo.ko_beginner
  ios:
    bundle_id: com.rensawamo.koBeginner
