name: core_designsystem
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  core_foundation:
    path: ../foundation
  core_utility:
    path: ../utility
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  flutter_localization: ^0.2.0
  intl: ^0.19.0

  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  widgetbook_generator: ^3.7.0
  flutter_gen_runner: ^5.6.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  assets:
    - assets/


## Package Settings
flutter_gen:
  output: lib/generated/flutter_gen
  colors:
    inputs:
      - assets/color/colors.xml
  integrations:
    flutter_svg: true
