// Mocks generated by Mockito 5.4.4 from annotations
// in core_dao/test/helper/helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core_foundation/foundation.dart' as _i6;
import 'package:core_model/quiz/quiz_model.dart' as _i4;
import 'package:core_repository/app_setting_info/app_setting_info_repository.dart'
    as _i5;
import 'package:core_repository/repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuizFavoriteSqlRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizFavoriteSqlRepositoryImpl extends _i1.Mock
    implements _i2.QuizFavoriteSqlRepositoryImpl {
  @override
  _i3.Future<int> insert(
    String? word,
    String? answer,
    String? sentence,
    String? translation,
    String? pronunciation,
    String? topicType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            word,
            answer,
            sentence,
            translation,
            pronunciation,
            topicType,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(String? word) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [word],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<String>> getTopicWords(String? topicType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopicWords,
          [topicType],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i4.Quiz>> getAllquizzes() => (super.noSuchMethod(
        Invocation.method(
          #getAllquizzes,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
      ) as _i3.Future<List<_i4.Quiz>>);

  @override
  _i3.Future<List<String>> getAllAnswers(String? topicType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAnswers,
          [topicType],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}

/// A class which mocks [QuizFavoriteSqlRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizFavoriteSqlRepository extends _i1.Mock
    implements _i2.QuizFavoriteSqlRepository {
  @override
  _i3.Future<int> insert(
    String? word,
    String? answer,
    String? sentence,
    String? translation,
    String? pronunciation,
    String? topicType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            word,
            answer,
            sentence,
            translation,
            pronunciation,
            topicType,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(String? word) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [word],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<String>> getTopicWords(String? topicType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopicWords,
          [topicType],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i4.Quiz>> getAllquizzes() => (super.noSuchMethod(
        Invocation.method(
          #getAllquizzes,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
      ) as _i3.Future<List<_i4.Quiz>>);

  @override
  _i3.Future<List<String>> getAllAnswers(String? topicType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAnswers,
          [topicType],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}

/// A class which mocks [AppSettingInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingInfo extends _i1.Mock implements _i5.AppSettingInfo {
  @override
  _i3.Future<void> changeAppInstallType(_i6.AppInstallType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeAppInstallType,
          [type],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setup() => (super.noSuchMethod(
        Invocation.method(
          #setup,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SharedPreferencesRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesRepositoryImpl extends _i1.Mock
    implements _i2.SharedPreferencesRepositoryImpl {
  @override
  _i3.Future<bool> save<T>(
    _i6.AppPrefsKey? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  T? fetch<T>(_i6.AppPrefsKey? key) => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  _i3.Future<bool> remove(_i6.AppPrefsKey? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
