name: core_router
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  core_utility:
    path: ../utility
  core_enums:
    path: ../enums
  core_views: 
    path: ../views
  feature_splash:
    path: ../../../packages/feature/splash
  feature_wordlist:
    path: ../../../packages/feature/wordlist
  feature_quiz:
    path: ../../../packages/feature/quiz
  feature_setting:
    path: ../../../packages/feature/setting
  feature_quiz_favorite:
    path: ../../../packages/feature/quiz_favorite
  feature_home:
    path: ../../../packages/feature/home

  hooks_riverpod: ^2.5.1
  go_router: ^14.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.3.7
  go_router_builder: ^2.3.4