name: core_utility
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  core_ui:
    path: ../../core/ui
  core_foundation:
   path: ../../core/foundation
  simple_logger: ^1.9.0+3
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9
  flutter_riverpod: ^2.5.1


  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
