name: core_model
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dependencies:
  freezed_annotation: ^2.4.1
  core_enums:
    path: ../enums
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  source_gen: 1.5.0
  flutter_gen_runner: ^5.4.0
  freezed: 2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0